/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.ServidorTCP;
import Model.Pessoa;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author laboratorio
 */
public class ServidorGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServidorGUI.class.getName());
    
private ArrayList<Pessoa> pessoas = new ArrayList<>();
private DefaultTableModel modelo;       

    /**
     * Creates new form ServidorGUI
     */
    public ServidorGUI() {
        initComponents();
        modelo = (DefaultTableModel) jTable1.getModel();

    new Thread(() -> iniciarServidor()).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logTxtA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        nomedoTxt = new javax.swing.JTextPane();
        salvarArquivoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logTxtA.setColumns(20);
        logTxtA.setRows(5);
        jScrollPane1.setViewportView(logTxtA);

        jLabel1.setText("AREA DE LOG");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome completo", "Data Nascimento", "Email Gerado"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setText("Digite o nome para o Arquivo txt :");

        jScrollPane3.setViewportView(nomedoTxt);

        salvarArquivoBtn.setText("Salvar no Arquivo");
        salvarArquivoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarArquivoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(salvarArquivoBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salvarArquivoBtn)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarArquivoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarArquivoBtnActionPerformed
        String nomeDoTXT = nomedoTxt.getText();
         
                ServidorTCP s = new ServidorTCP();
                try{
                s.salvarPessoas(pessoas,nomeDoTXT);
                JOptionPane.showMessageDialog(this,"Arquivo Salvo/Atualizado com Sucesso"); 
                
                }catch(Exception e) {
                     JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage()); 
                }
    }//GEN-LAST:event_salvarArquivoBtnActionPerformed

private void log(String texto) {
        logTxtA.append(texto + "\n");
}
    
    private void iniciarServidor() {

    try {

        ServerSocket servidor = new ServerSocket(50000);

        logTxtA.append("Servidor iniciado na porta 50000.\n");

        while (true) {

            Socket cliente = servidor.accept();

            logTxtA.append("Cliente conectado.\n");

            new Thread(() -> atenderCliente(cliente)).start();
        }

    } catch (Exception e) {

        logTxtA.append("Erro: " + e.getMessage() + "\n");
    }
}
   
private void adicionarTabela(Pessoa pessoa) {

        modelo.addRow(new Object[]{
            pessoa.getNome(),
            pessoa.getDataNascimento(),
            pessoa.getEmail()
        });

} 
   
private void atenderCliente(Socket cliente) {

    try {

        ObjectInputStream entrada =
                new ObjectInputStream(cliente.getInputStream());

        Pessoa pessoa = (Pessoa) entrada.readObject();

        Pessoa existente = null;
        
        ServidorTCP s = new ServidorTCP();

        synchronized (pessoas) {

            for (Pessoa p : pessoas) {

                if (p.getNome().equalsIgnoreCase(pessoa.getNome())
                        && p.getDataNascimento().equals(pessoa.getDataNascimento())) {

                    existente = p;
                    break;
                }
            }

            if (existente == null) {

                pessoa.setEmail(s.gerarEmail(pessoa));

                pessoas.add(pessoa);

                adicionarTabela(pessoa);

                log("Pessoa cadastrada: " + pessoa.getNome());

                existente = pessoa;
               
            } else {

                log("Pessoa já cadastrada: " + pessoa.getNome());
            }
        }

        ObjectOutputStream saida =
                new ObjectOutputStream(cliente.getOutputStream());

        saida.writeObject(existente);
        saida.flush();
        cliente.close();

    } catch (Exception e) {

        log("Erro: " + e.getMessage());
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServidorGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea logTxtA;
    private javax.swing.JTextPane nomedoTxt;
    private javax.swing.JButton salvarArquivoBtn;
    // End of variables declaration//GEN-END:variables
}
