/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ExercicioFixacao;


import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author laboratorio
 */
public class ServidorGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ServidorGUI.class.getName());
    
    private ArrayList<Pessoa> pessoas = new ArrayList<>();
private DefaultTableModel modelo;       

    /**
     * Creates new form ServidorGUI
     */
    public ServidorGUI() {
        initComponents();
        modelo = (DefaultTableModel) jTable1.getModel();

    new Thread(() -> iniciarServidor()).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logTxtA = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logTxtA.setColumns(20);
        logTxtA.setRows(5);
        jScrollPane1.setViewportView(logTxtA);

        jLabel1.setText("AREA DE LOG");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome completo", "Data Nascimento", "Email Gerado"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void iniciarServidor() {

    try {

        ServerSocket servidor = new ServerSocket(50000);

        logTxtA.append("Servidor iniciado na porta 50000.\n");

        while (true) {

            Socket cliente = servidor.accept();

            logTxtA.append("Cliente conectado.\n");

            new Thread(() -> atenderCliente(cliente)).start();
        }

    } catch (Exception e) {

        logTxtA.append("Erro: " + e.getMessage() + "\n");
    }
}

private void atenderCliente(Socket cliente) {

    try {

        ObjectInputStream entrada =
                new ObjectInputStream(cliente.getInputStream());

        Pessoa pessoa = (Pessoa) entrada.readObject();

        Pessoa existente = null;

        synchronized (pessoas) {

            for (Pessoa p : pessoas) {

                if (p.getNome().equalsIgnoreCase(pessoa.getNome())
                        && p.getDataNascimento().equals(pessoa.getDataNascimento())) {

                    existente = p;
                    break;
                }
            }

            if (existente == null) {

                pessoa.setEmail(gerarEmail(pessoa));

                pessoas.add(pessoa);

                adicionarTabela(pessoa);

                log("Pessoa cadastrada: " + pessoa.getNome());

                existente = pessoa;

            } else {

                log("Pessoa já cadastrada: " + pessoa.getNome());
            }
        }

        ObjectOutputStream saida =
                new ObjectOutputStream(cliente.getOutputStream());

        saida.writeObject(existente);
        saida.flush();

        cliente.close();

    } catch (Exception e) {

        log("Erro: " + e.getMessage());
    }
}

private String gerarEmail(Pessoa pessoa) {

    String[] nomes = pessoa.getNome().trim().toLowerCase().split("\\s+");

    String primeiro = nomes[0];
    String ultimo = nomes[nomes.length - 1];

    String ano = pessoa.getDataNascimento().substring(6);

    return primeiro + "." + ultimo + "." + ano + "@ufn.edu.br";
}

private void adicionarTabela(Pessoa pessoa) {

    SwingUtilities.invokeLater(() -> {

        modelo.addRow(new Object[]{
            pessoa.getNome(),
            pessoa.getDataNascimento(),
            pessoa.getEmail()
        });
    });
}

private void log(String texto) {

    SwingUtilities.invokeLater(() -> {
        logTxtA.append(texto + "\n");
    });
}
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ServidorGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea logTxtA;
    // End of variables declaration//GEN-END:variables
}
